# Generated by Django 4.2.4 on 2023-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/one'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='img',
            field=models.ImageField(upload_to='products/multi'),
        ),
    ]
