# Generated by Django 4.2.4 on 2023-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='by_session',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
