# Generated by Django 4.2.4 on 2023-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_favorite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_ID_Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id_rand', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
