# Generated by Django 4.2.4 on 2023-09-17 14:54

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_reviewrating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_storeg_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='img',
            field=models.ImageField(upload_to=store.models.image_upload),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='by_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.favorite_storeg_id'),
        ),
    ]
