# Generated by Django 4.2.4 on 2023-09-18 22:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_information_product_information_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color_name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size_name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
