# Generated by Django 4.2.4 on 2023-10-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_category_category_name_ar_color_color_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
