# Generated by Django 4.2.4 on 2023-10-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_avg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_name_ar',
        ),
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
    ]
