# Generated by Django 4.2.4 on 2023-10-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name_ar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='color',
            name='stock',
            field=models.IntegerField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name_ar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.IntegerField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
