# Generated by Django 4.2.4 on 2023-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_color_color_code_alter_color_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
