# Generated by Django 4.2.4 on 2023-10-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_color_size_remove_size_color_color_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='color_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
