# Generated by Django 4.2.4 on 2023-10-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_color_customizations_delete_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizations',
            options={'verbose_name_plural': 'Customizations'},
        ),
    ]
