# Generated by Django 4.2.4 on 2023-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_reviewrating_rtl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='rtl',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='direction',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
