# Generated by Django 4.2.4 on 2023-11-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_reviewrating_rtl_reviewrating_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='by_session',
        ),
        migrations.DeleteModel(
            name='Favorite_storeg_id',
        ),
    ]
