# Generated by Django 4.2.7 on 2023-12-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_product_favorits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='information_ar',
        ),
    ]
