# Generated by Django 4.2.7 on 2023-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_codes',
            name='validate_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount_codes',
            name='validate_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
