# Generated by Django 4.2.4 on 2023-09-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_active',
            new_name='x',
        ),
    ]
