# Generated by Django 4.2.4 on 2023-09-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_active_accounts_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='x',
            new_name='is_active',
        ),
    ]
