# Generated by Django 4.2.4 on 2023-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_x_accounts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='validation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
