# Generated by Django 4.2.4 on 2023-09-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_validation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='session_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
