# Generated by Django 4.2.4 on 2023-09-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounts_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='right_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='sending_count',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
