# Generated by Django 4.2.4 on 2023-09-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_right_send_accounts_sending_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='right_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='sending_count',
            field=models.IntegerField(blank=True, default=5, max_length=10, null=True),
        ),
    ]
