# Generated by Django 4.2.4 on 2023-09-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounts_right_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='sending_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
