# Generated by Django 4.2.4 on 2023-09-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accounts_sending_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
