# Generated by Django 4.2.4 on 2023-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_is_superadmin_accounts_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='profile_pictuer',
        ),
    ]
