# Generated by Django 4.2.4 on 2023-09-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accounts_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='country',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='phone_numper',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='state',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numper', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('profile_pictuer', models.ImageField(blank=True, null=True, upload_to='userprofile')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
