# Generated by Django 4.2.4 on 2023-09-18 22:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_profile_pictuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='right_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pictuer',
            field=models.ImageField(blank=True, default='userprofile/7603668.jpg', null=True, upload_to=accounts.models.image_upload),
        ),
    ]
