# Generated by Django 4.2.4 on 2023-09-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('accounts', '0015_alter_accounts_right_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount_cods',
            field=models.ManyToManyField(blank=True, null=True, to='discounts.discount_codes'),
        ),
    ]
