# Generated by Django 4.2.4 on 2023-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_discount_cods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='session_code',
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_popup',
            field=models.BooleanField(default=False),
        ),
    ]
