# Generated by Django 4.2.4 on 2023-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_is_popup_accounts_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
