# Generated by Django 4.2.4 on 2023-11-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_accounts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
