# Generated by Django 4.2.4 on 2023-11-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_accounts_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
