# Generated by Django 4.2.4 on 2023-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_tags_tags_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
