# Generated by Django 4.2.4 on 2023-09-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_tag1_blog_tag2_blog_tag3_delete_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag3',
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
