# Generated by Django 4.2.4 on 2023-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tags_criated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='criated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
