# Generated by Django 4.2.4 on 2023-09-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_tags_criated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
