# Generated by Django 4.2.4 on 2023-09-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_slug_alter_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_ar',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_ar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
