# Generated by Django 4.2.4 on 2023-11-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rply_for_rply', to='blog.reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
