# Generated by Django 4.2.4 on 2023-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_reply_parent_reply_alter_reply_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
