# Generated by Django 4.2.4 on 2023-12-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_reply_reply_to_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
    ]
