# Generated by Django 4.2.4 on 2023-09-19 22:05

import cart.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_temporary_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cart.models.random_code, max_length=10)),
                ('discount', models.IntegerField(max_length=100)),
                ('validate_from', models.DateTimeField()),
                ('validate_to', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.discount_codes'),
        ),
    ]
