# Generated by Django 4.2.4 on 2023-09-20 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_remove_cartitem_discount_code_discount_codes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_codes',
            name='user',
        ),
        migrations.AddField(
            model_name='discount_codes',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
