# Generated by Django 4.2.4 on 2023-09-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_discount_codes_user_discount_codes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_codes',
            name='user',
        ),
    ]
