# Generated by Django 4.2.4 on 2023-11-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cartitem_color_alter_cartitem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temporary_cart',
        ),
    ]
