# Generated by Django 4.2.4 on 2023-11-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user_alter_orderproduct_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('When Recieving', 'When Recieving'), ('Paypal', 'Paypal'), ('Stripe', 'Stripe')], default='When Recieving', max_length=15),
        ),
    ]
