# Generated by Django 4.2.4 on 2023-11-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_status_remove_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
    ]
