# Generated by Django 4.2.4 on 2023-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('When Recieving', 'When Recieving'), ('Paypal', 'Paypal'), ('Stripe', 'Stripe'), ('None', 'None')], default='None', max_length=15),
        ),
    ]
