# Generated by Django 4.2.4 on 2023-11-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_payment_invoice_payment_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payerid',
            new_name='payer_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
