# Generated by Django 4.2.4 on 2023-11-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_payerid_payment_payer_id_payment_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
