# Generated by Django 4.2.4 on 2023-11-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_reviewrating_rtl_reviewrating_direction'),
        ('orders', '0010_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color_list'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size_list'),
        ),
    ]
