# Generated by Django 4.2.4 on 2023-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderproduct_color_alter_orderproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
