# Generated by Django 4.2.4 on 2023-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Delivery is in progress', 'Delivery is in progress')], default='Delivery is in progress', max_length=100),
        ),
    ]
