# Generated by Django 4.2.7 on 2023-12-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_E_mesg',
            field=models.BooleanField(default=False),
        ),
    ]
